export const CLASSES = {
  'WARRIOR': 'Warrior',
  'WARRIOR_0_0': 'Vanguard',
  'WARRIOR_0_1': 'General',
  'WARRIOR_0_2': 'Grand General',
  'WARRIOR_1_0': 'Spearman',
  'WARRIOR_1_1': 'Impaler',
  'WARRIOR_1_2': 'Sin Impaler',
  'SWORDSMAN': 'Swordsman',
  'SWORDSMAN_0_0': 'Soldier',
  'SWORDSMAN_0_1': 'Knight',
  'SWORDSMAN_0_2': 'Royal Knight',
  'SWORDSMAN_1_0': 'Dual Sword',
  'SWORDSMAN_1_1': 'Slayer',
  'SWORDSMAN_1_2': 'Mad Slayer',
  'HUNTER': 'Hunter',
  'HUNTER_0_0': 'Archer',
  'HUNTER_0_1': 'Sniper',
  'HUNTER_0_2': 'Phantom Sniper',
  'HUNTER_1_0': 'Rogue',
  'HUNTER_1_1': 'Assassin',
  'HUNTER_1_2': 'Shadow Assassin',
  'HUNTER_2_0': 'Fencer',
  'HUNTER_2_1': 'Chaser',
  'HUNTER_2_2': 'Dread Chaser',
  'WITCH': 'Witch',
  'WITCH_0_0': 'Professor',
  'WITCH_0_1': 'Mage',
  'WITCH_0_2': 'Archmage',
  'WITCH_1_0': 'Scholar',
  'WITCH_1_1': 'Cleric',
  'WITCH_1_2': 'Saint Cleric',
}

export const DUNGEONS = {
  'DUNGEON_0_0': 'KODSHEE (Beginner)',
  'DUNGEON_0_1': 'KODSHEE (Intermediate)',
  'DUNGEON_0_2': 'KODSHEE (Advanced)',
  'DUNGEON_0_3': 'KODSHEE (Superior)',
  'DUNGEON_1_0': 'TIARAK (Beginner)',
  'DUNGEON_1_1': 'TIARAK (Intermediate)',
  'DUNGEON_1_2': 'TIARAK (Advanced)',
  'DUNGEON_1_3': 'TIARAK (Superior)',
}